#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"

TODO(alexander-soare):
  - Remove reliance on diffusers for DDPMScheduler and LR scheduler.
"""

import math
from collections import deque
from collections.abc import Callable

import einops
import numpy as np
import torch
import torch.nn.functional as F  # noqa: N812
import torchvision
from diffusers.schedulers.scheduling_ddim import DDIMScheduler
from diffusers.schedulers.scheduling_ddpm import DDPMScheduler
from torch import Tensor, nn

from lerobot.policies.diffusion.configuration_diffusion import DiffusionConfig
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import (
    get_device_from_parameters,
    get_dtype_from_parameters,
    get_output_shape,
    populate_queues,
)
from lerobot.utils.constants import ACTION, OBS_ENV_STATE, OBS_IMAGES, OBS_STATE


class DiffusionPolicy(PreTrainedPolicy):
    """
    Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"
    (paper: https://huggingface.co/papers/2303.04137, code: https://github.com/real-stanford/diffusion_policy).
    """

    config_class = DiffusionConfig
    name = "diffusion"

    def __init__(
        self,
        config: DiffusionConfig,
    ):
        """
        Args:
            config: Policy configuration class instance or None, in which case the default instantiation of
                the configuration class is used.
            dataset_stats: Dataset statistics to be used for normalization. If not passed here, it is expected
                that they will be passed with a call to `load_state_dict` before the policy is used.
        """
        super().__init__(config)
        config.validate_features()
        self.config = config

        # queues are populated during rollout of the policy, they contain the n latest observations and actions
        self._queues = None

        self.diffusion = DiffusionModel(config)  # 创建扩散模型

        self.reset()

    def get_optim_params(self) -> dict:
        return self.diffusion.parameters()

    def reset(self):
        """Clear observation and action queues. Should be called on `env.reset()`"""
        self._queues = {
            OBS_STATE: deque(maxlen=self.config.n_obs_steps),  # 状态观测队列，长度为 n_obs_steps=2
            ACTION: deque(maxlen=self.config.n_action_steps),  # 动作队列，长度为 n_action_steps=8
        }
        if self.config.image_features:
            self._queues[OBS_IMAGES] = deque(maxlen=self.config.n_obs_steps)  # 图像观测队列
        if self.config.env_state_feature:
            self._queues[OBS_ENV_STATE] = deque(maxlen=self.config.n_obs_steps)  # 环境状态队列

    @torch.no_grad()
    def predict_action_chunk(self, batch: dict[str, Tensor]) -> Tensor:
        """Predict a chunk of actions given environment observations."""
        # stack n latest observations from the queue
        # 将队列中的观测值堆叠起来：batch 中每个键的值形状为 (batch_size, n_obs_steps, feature_dim)
        batch = {k: torch.stack(list(self._queues[k]), dim=1) for k in batch if k in self._queues}
        actions = self.diffusion.generate_actions(batch)  # 生成动作序列

        return actions  # (batch_size, horizon, action_dim)

    @torch.no_grad()
    def select_action(self, batch: dict[str, Tensor]) -> Tensor:
        """Select a single action given environment observations.

        This method handles caching a history of observations and an action trajectory generated by the
        underlying diffusion model. Here's how it works:
          - `n_obs_steps` steps worth of observations are cached (for the first steps, the observation is
            copied `n_obs_steps` times to fill the cache).
          - The diffusion model generates `horizon` steps worth of actions.
          - `n_action_steps` worth of actions are actually kept for execution, starting from the current step.
        Schematically this looks like:
            ----------------------------------------------------------------------------------------------
            (legend: o = n_obs_steps, h = horizon, a = n_action_steps)
            |timestep            | n-o+1 | n-o+2 | ..... | n     | ..... | n+a-1 | n+a   | ..... | n-o+h |
            |observation is used | YES   | YES   | YES   | YES   | NO    | NO    | NO    | NO    | NO    |
            |action is generated | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   |
            |action is used      | NO    | NO    | NO    | YES   | YES   | YES   | NO    | NO    | NO    |
            ----------------------------------------------------------------------------------------------
        Note that this means we require: `n_action_steps <= horizon - n_obs_steps + 1`. Also, note that
        "horizon" may not the best name to describe what the variable actually means, because this period is
        actually measured from the first observation which (if `n_obs_steps` > 1) happened in the past.

        生成动作的缓存机制详解：

        时间步 t=0:
        观测：[t=-1, t=0]  ← 使用这 2 步观测
        生成动作：[a₋₁, a₀, a₁, a₂, a₃, a₄, a₅, a₆, a₇, a₈, ..., a₁₄]  (16 步)
        执行动作：a₀  ← 只执行当前步！
        缓存动作：[a₁, a₂, a₃, a₄, a₅, a₆, a₇]  ← 剩下的 7 步存入队列

        时间步 t=1:
        观测：[t=0, t=1]  ← 新的观测
        队列中有：[a₁, a₂, a₃, a₄, a₅, a₆, a₇]  ← 直接使用缓存的动作！
        执行动作：a₁  ← 从队列取，不需要重新生成
        
        ... (继续使用缓存直到 t=7)

        时间步 t=8:
        观测：[t=7, t=8]  ← 队列空了！
        队列中：[]  ← 需要重新生成
        生成新动作：[a₇, a₈, ..., a₂₂]  (新的 16 步)
        执行动作：a₈
        缓存动作：[a₉, a₁₀, ..., a₂₂]  ← 缓存 15 步（去掉已执行的）
        """
        # NOTE: for offline evaluation, we have action in the batch, so we need to pop it out
        if ACTION in batch:
            batch.pop(ACTION)  # 移除 batch 中的 action（如果存在），避免影响推理

        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            # 将多个相机图像堆叠到单个键中：(batch_size, n_obs_steps, num_cameras, C, H, W)
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        # NOTE: It's important that this happens after stacking the images into a single key.
        self._queues = populate_queues(self._queues, batch)  # 填充观测队列

        if len(self._queues[ACTION]) == 0:
            # 如果动作队列为空，生成新的动作序列
            actions = self.predict_action_chunk(batch)  # (batch_size, horizon, action_dim)
            self._queues[ACTION].extend(actions.transpose(0, 1))  # 转置后加入队列，队列期望 (horizon, batch_size, action_dim)

        action = self._queues[ACTION].popleft()  # 取出当前步的动作
        return action  # (batch_size, action_dim)

    def forward(self, batch: dict[str, Tensor]) -> tuple[Tensor, None]:
        """Run the batch through the model and compute the loss for training or validation."""
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            # 将多个相机图像堆叠到单个键中：(batch_size, n_obs_steps, num_cameras, C, H, W)
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        loss = self.diffusion.compute_loss(batch)  # 计算扩散模型损失
        # no output_dict so returning None
        return loss, None  # (标量损失值，None)


def _make_noise_scheduler(name: str, **kwargs: dict) -> DDPMScheduler | DDIMScheduler:
    """
    Factory for noise scheduler instances of the requested type. All kwargs are passed
    to the scheduler.
    """
    if name == "DDPM":
        return DDPMScheduler(**kwargs)
    elif name == "DDIM":
        return DDIMScheduler(**kwargs)
    else:
        raise ValueError(f"Unsupported noise scheduler type {name}")


class DiffusionModel(nn.Module):
    """扩散模型，包含 UNet、噪声调度器等核心组件"""
    
    def __init__(self, config: DiffusionConfig):
        super().__init__()
        self.config = config

        # Build observation encoders (depending on which observations are provided).
        # 计算全局条件维度：状态特征维度
        global_cond_dim = self.config.robot_state_feature.shape[0]  # 例如：state_dim=2
        
        if self.config.image_features:
            num_images = len(self.config.image_features)  # 相机数量，例如：1
            if self.config.use_separate_rgb_encoder_per_camera:
                # 为每个相机使用独立的 RGB 编码器
                encoders = [DiffusionRgbEncoder(config) for _ in range(num_images)]
                self.rgb_encoder = nn.ModuleList(encoders)
                global_cond_dim += encoders[0].feature_dim * num_images  # 每个编码器输出 feature_dim=64
            else:
                # 所有相机共享一个 RGB 编码器
                self.rgb_encoder = DiffusionRgbEncoder(config)
                global_cond_dim += self.rgb_encoder.feature_dim * num_images  # feature_dim=64 * num_images=1
        
        if self.config.env_state_feature:
            global_cond_dim += self.config.env_state_feature.shape[0]  # 添加环境状态特征维度

        # 创建条件 UNet，global_cond_dim 需要乘以 n_obs_steps 因为要对每个时间步的条件进行编码
        self.unet = DiffusionConditionalUnet1d(config, global_cond_dim=global_cond_dim * config.n_obs_steps)
        # global_cond_dim = (state_dim + image_feature_dim * num_images) * n_obs_steps
        # 例如：(2 + 64 * 1) * 2 = 132

        # 创建噪声调度器（用于前向加噪和反向去噪）
        self.noise_scheduler = _make_noise_scheduler(
            config.noise_scheduler_type,
            num_train_timesteps=config.num_train_timesteps,  # 100
            beta_start=config.beta_start,  # 0.0001
            beta_end=config.beta_end,  # 0.02
            beta_schedule=config.beta_schedule,  # "squaredcos_cap_v2"
            clip_sample=config.clip_sample,
            clip_sample_range=config.clip_sample_range,
            prediction_type=config.prediction_type,  # "epsilon"
        )

        # 设置推理时的去噪步数
        if config.num_inference_steps is None:
            self.num_inference_steps = self.noise_scheduler.config.num_train_timesteps  # 默认 100
        else:
            self.num_inference_steps = config.num_inference_steps

    # ========= inference  ============
    def conditional_sample(
        self, batch_size: int, global_cond: Tensor | None = None, generator: torch.Generator | None = None
    ) -> Tensor:
        """条件采样生成动作序列
        
        Args:
            batch_size: 批次大小
            global_cond: 全局条件特征 (batch_size, global_cond_dim)
            generator: 随机数生成器
        
        Returns:
            Tensor: 生成的动作序列 (batch_size, horizon, action_dim)
        """
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        # Sample prior. 从标准正态分布采样噪声作为初始动作序列
        sample = torch.randn(
            size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
            # (batch_size=64, horizon=16, action_dim=2)
            dtype=dtype,
            device=device,
            generator=generator,
        )

        self.noise_scheduler.set_timesteps(self.num_inference_steps)  # 设置去噪时间步

        # 逐步去噪
        for t in self.noise_scheduler.timesteps:
            # Predict model output. 预测噪声或样本
            model_output = self.unet(
                sample,  # (batch_size, horizon, action_dim)
                torch.full(sample.shape[:1], t, dtype=torch.long, device=sample.device),  # (batch_size,) 填充时间步 t
                global_cond=global_cond,  # (batch_size, global_cond_dim)
            )  # (batch_size, horizon, action_dim)
            # Compute previous image: x_t -> x_t-1 计算前一步的样本
            sample = self.noise_scheduler.step(model_output, t, sample, generator=generator).prev_sample
            # (batch_size, horizon, action_dim)

        return sample  # (batch_size, horizon, action_dim)

    def _prepare_global_conditioning(self, batch: dict[str, Tensor]) -> Tensor:
        """Encode image features and concatenate them all together along with the state vector.
        准备全局条件特征：编码图像特征并与状态向量拼接
        
        Args:
            batch: 包含观测数据的字典
        
        Returns:
            Tensor: 全局条件特征 (batch_size, global_cond_dim)
        """
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]  # batch_size=64, n_obs_steps=2
        global_cond_feats = [batch[OBS_STATE]]  # [(batch_size, n_obs_steps, state_dim=2)]
        
        # Extract image features.
        if self.config.image_features:
            if self.config.use_separate_rgb_encoder_per_camera:
                # Combine batch and sequence dims while rearranging to make the camera index dimension first.
                # 重排维度：(batch, s, n, ...) -> (n, batch*s, ...)
                images_per_camera = einops.rearrange(batch[OBS_IMAGES], "b s n ... -> n (b s) ...")
                # (num_cameras, batch_size * n_obs_steps, C, H, W)
                
                img_features_list = torch.cat(
                    [
                        encoder(images)  # 每个编码器输出 (batch_size * n_obs_steps, feature_dim)
                        for encoder, images in zip(self.rgb_encoder, images_per_camera, strict=True)
                    ]
                )
                # (num_cameras * batch_size * n_obs_steps, feature_dim)
                
                # Separate batch and sequence dims back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                # 重排回原始维度：(n, b, s, ...) -> (b, s, n*...)
                img_features = einops.rearrange(
                    img_features_list, "(n b s) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
                # (batch_size, n_obs_steps, num_cameras * feature_dim)
            else:
                # Combine batch, sequence, and "which camera" dims before passing to shared encoder.
                # 重排维度：(b, s, n, ...) -> (b*s*n, ...) 以便通过共享编码器
                img_features = self.rgb_encoder(
                    einops.rearrange(batch[OBS_IMAGES], "b s n ... -> (b s n) ...")
                )
                # (batch_size * n_obs_steps * num_cameras, feature_dim)
                
                # Separate batch dim and sequence dim back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                # 重排回原始维度：(b*s*n, ...) -> (b, s, n*...)
                img_features = einops.rearrange(
                    img_features, "(b s n) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
                # (batch_size, n_obs_steps, num_cameras * feature_dim)
            global_cond_feats.append(img_features)  # [(batch, n_obs, state_dim), (batch, n_obs, img_feature_dim)]

        if self.config.env_state_feature:
            global_cond_feats.append(batch[OBS_ENV_STATE])  # 添加环境状态特征

        # Concatenate features then flatten to (B, global_cond_dim).
        # 拼接特征并展平：(batch, n_obs_steps, state_dim + img_feature_dim) -> (batch, n_obs_steps * (state_dim 2 + img_feature_dim 64))
        return torch.cat(global_cond_feats, dim=-1).flatten(start_dim=1)
        # (batch_size, global_cond_dim) 例如：(64, 132)

    def generate_actions(self, batch: dict[str, Tensor]) -> Tensor:
        """
        This function expects `batch` to have:
        {
            "observation.state": (B, n_obs_steps, state_dim)
            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)
        }
        
        生成动作序列
        """
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]  # batch_size=64, n_obs_steps=2
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim) 例如：(64, 132)

        # run sampling 运行采样过程
        actions = self.conditional_sample(batch_size, global_cond=global_cond)
        # (batch_size, horizon, action_dim) 例如：(64, 16, 2)

        # Extract `n_action_steps` steps worth of actions (from the current observation).
        # 提取 n_action_steps 个动作（从当前观测开始）
        start = n_obs_steps - 1  # 起始索引：2 - 1 = 1
        end = start + self.config.n_action_steps  # 结束索引：1 + 8 = 9
        actions = actions[:, start:end]  # (batch_size, n_action_steps, action_dim) 例如：(64, 8, 2)

        return actions

    def compute_loss(self, batch: dict[str, Tensor]) -> Tensor:
        """
        This function expects `batch` to have (at least):
        {
            "observation.state": (B, n_obs_steps, state_dim)
            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)
            "action": (B, horizon, action_dim)
            "action_is_pad": (B, horizon)
        }
        
        计算扩散模型损失
        """
        # Input validation.
        assert set(batch).issuperset({OBS_STATE, ACTION, "action_is_pad"})
        assert OBS_IMAGES in batch or OBS_ENV_STATE in batch
        n_obs_steps = batch[OBS_STATE].shape[1]  # 2
        horizon = batch[ACTION].shape[1]  # 16
        assert horizon == self.config.horizon
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim) 例如：(64, 132)

        # Forward diffusion.
        trajectory = batch[ACTION]  # (batch_size, horizon, action_dim) 例如：(64, 16, 2)
        
        # Sample noise to add to the trajectory. 采样噪声
        eps = torch.randn(trajectory.shape, device=trajectory.device)
        # (batch_size, horizon, action_dim) 例如：(64, 16, 2)
        
        # Sample a random noising timestep for each item in the batch. 采样随机时间步
        timesteps = torch.randint(
            low=0,
            high=self.noise_scheduler.config.num_train_timesteps,  # 100
            size=(trajectory.shape[0],),  # (batch_size,)
            device=trajectory.device,
        ).long()
        # (batch_size,) 例如：(64,)
        
        # Add noise to the clean trajectories according to the noise magnitude at each timestep.
        # 根据时间步的噪声强度向轨迹添加噪声
        noisy_trajectory = self.noise_scheduler.add_noise(trajectory, eps, timesteps)
        # (batch_size, horizon, action_dim) 例如：(64, 16, 2)

        # Run the denoising network (that might denoise the trajectory, or attempt to predict the noise).
        # 运行去噪网络预测噪声
        pred = self.unet(noisy_trajectory, timesteps, global_cond=global_cond)
        # (batch_size, horizon, action_dim) 例如：(64, 16, 2)

        # Compute the loss.
        # The target is either the original trajectory, or the noise.
        if self.config.prediction_type == "epsilon":
            target = eps  # 预测噪声
        elif self.config.prediction_type == "sample":
            target = batch[ACTION]  # 预测原始轨迹
        else:
            raise ValueError(f"Unsupported prediction type {self.config.prediction_type}")

        # 计算均方误差损失
        loss = F.mse_loss(pred, target, reduction="none")
        # (batch_size, horizon, action_dim) 例如：(64, 16, 2)

        # Mask loss wherever the action is padded with copies (edges of the dataset trajectory).
        # 如果动作有填充，则掩码损失
        if self.config.do_mask_loss_for_padding:
            if "action_is_pad" not in batch:
                raise ValueError(
                    "You need to provide 'action_is_pad' in the batch when "
                    f"{self.config.do_mask_loss_for_padding=}."
                )
            in_episode_bound = ~batch["action_is_pad"]  # (batch_size, horizon)
            loss = loss * in_episode_bound.unsqueeze(-1)  # (batch_size, horizon, action_dim)

        return loss.mean()  # 标量


class SpatialSoftmax(nn.Module):
    """
    Spatial Soft Argmax operation described in "Deep Spatial Autoencoders for Visuomotor Learning" by Finn et al.
    (https://huggingface.co/papers/1509.06113). A minimal port of the robomimic implementation.

    At a high level, this takes 2D feature maps (from a convnet/ViT) and returns the "center of mass"
    of activations of each channel, i.e., keypoints in the image space for the policy to focus on.

    Example: take feature maps of size (512x10x12). We generate a grid of normalized coordinates (10x12x2):
    -----------------------------------------------------
    | (-1., -1.)   | (-0.82, -1.)   | ... | (1., -1.)   |
    | (-1., -0.78) | (-0.82, -0.78) | ... | (1., -0.78) |
    | ...          | ...            | ... | ...         |
    | (-1., 1.)    | (-0.82, 1.)    | ... | (1., 1.)    |
    -----------------------------------------------------
    This is achieved by applying channel-wise softmax over the activations (512x120) and computing the dot
    product with the coordinates (120x2) to get expected points of maximal activation (512x2).

    The example above results in 512 keypoints (corresponding to the 512 input channels). We can optionally
    provide num_kp != None to control the number of keypoints. This is achieved by a first applying a learnable
    linear mapping (in_channels, H, W) -> (num_kp, H, W).
    
    空间 Softmax 操作，从 2D 特征图中提取关键点坐标
      ═══════════════════════════════════════════════════════════════════════════════
    维度压缩详解：512 通道 → 32 个关键点
    ═══════════════════════════════════════════════════════════════════════════════
    
    完整维度变化流程（以 PushT 为例）：
    
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 1: 骨干网络输出 (ResNet18)                                                │
    │ 形状：(B, 512, 3, 3)                                                         │
    │   - B = batch_size (例如 128)                                                │
    │   - 512 = 通道数（特征数量）                                                    │
    │   - 3×3 = 空间网格大小                                                        │
    └─────────────────────────────────────────────────────────────────────────────┘
                                    ↓  【关键步骤】1×1 卷积降维
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 2: 1×1 卷积 (Conv2d(512, 32, kernel_size=1))                              │
    │ 形状：(B, 32, 3, 3)  ← 通道数从 512 压缩到 32                                    │
    │                                                                             │
    │ 1×1 卷积的作用：                                                              │
    │   - 对每个空间位置独立操作                                                    │
    │   - 将 512 维特征向量线性组合为 32 维                                           │
    │   - 保持空间尺寸不变 (3×3)                                                    │
    │                                                                             │
    │ 可视化：                                                                     │
    │   空间位置 (0,0): [512 维特征] → Conv2d(512→32) → [32 维特征]                   │
    │   空间位置 (0,1): [512 维特征] → Conv2d(512→32) → [32 维特征]                   │
    │   ...                                                                        │
    │   空间位置 (2,2): [512 维特征] → Conv2d(512→32) → [32 维特征]                   │
    └─────────────────────────────────────────────────────────────────────────────┘
                                    ↓ 展平空间维度
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 3: Reshape 展平                                                          │
    │ 形状：(B×32, 9)  ← 3×3=9 个空间位置展平                                         │
    │ 解释：每个样本有 32 个通道，每个通道有 9 个空间激活值                               │
    └─────────────────────────────────────────────────────────────────────────────┘
                                    ↓  Spatial Softmax
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 4: Spatial Softmax 归一化                                                 │
    │ 形状：(B×32, 9)  ← 每个通道的 9 个值加起来等于 1                                  │
    │                                                                             │
    │ Softmax 的作用：                                                              │
    │   - 将 9 个空间激活值转换为概率分布                                             │
    │   - 高激活区域获得高概率                                                      │
    │                                                                             │
    │ 示例（通道 k 的 9 个空间值）：                                                    │
    │   原始值：[0.2, 0.1, 0.3, 0.05, 0.25, 0.05, 0.02, 0.01, 0.02]                 │
    │   Softmax 后：[0.15, 0.08, 0.20, 0.05, 0.18, 0.05, 0.04, 0.03, 0.02]          │
    │   (所有值加起来 = 1.0)                                                        │
    └─────────────────────────────────────────────────────────────────────────────┘
                                    ↓  @ pos_grid (计算期望坐标)
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 5: 计算期望坐标（点积）                                                    │
    │ 形状：(B×32, 2)  ← 每个通道输出一个 (x,y) 坐标                                   │
    │                                                                             │
    │ 计算公式：                                                                   │
    │   对于每个通道 k:                                                             │
    │     期望 x = Σ(注意力权重 [i] × 位置 i 的 x 坐标)                                  │
    │     期望 y = Σ(注意力权重 [i] × 位置 i 的 y 坐标)                                  │
    │                                                                             │
    │ 结果：每个通道输出一个 (x, y) 坐标，表示该通道激活重心的位置                       │
    └─────────────────────────────────────────────────────────────────────────────┘
                                    ↓  Reshape
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │ 步骤 6: 重塑为最终形状                                                         │
    │ 形状：(B, 32, 2)  ← 32 个关键点，每个点有 (x, y) 坐标                              │
    │                                                                             │
    │ 最终输出：32 个关键点的归一化坐标（范围 [-1, 1]）                                 │
    └─────────────────────────────────────────────────────────────────────────────┘
    
    ═══════════════════════════════════════════════════════════════════════════════
    为什么需要 SpatialSoftmax？
    ═══════════════════════════════════════════════════════════════════════════════
    
    1. 空间特征压缩：
       - 直接展平：512 × 3 × 3 = 4608 维 → 维度太高
       - SpatialSoftmax: 32 × 2 = 64 维 → 紧凑且保留空间信息
    
    2. 提取空间关键点坐标：
       - 不是简单的平均池化或最大池化
       - 输出关键点的 (x, y) 坐标（归一化到 [-1, 1]）
       - 每个关键点代表图像中一个重要位置
    
    3. 对机器人策略的重要性：
       对于 visuomotor 策略（视觉 - 运动策略）：
       
       | 池化方式       | 输出        | 缺点                          │
       |---------------|-------------|-------------------------------│
       | 全局平均池化   | (B, 512)    | 丢失空间位置信息               │
       | 最大池化       | (B, 512)    | 只保留最强激活，丢失结构        │
       | SpatialSoftmax| (B, 32, 2)  | 保留关键物体的空间位置 ✅       │
       
       示例（PushT 任务）：
       - 关键点 1: 推杆的末端位置 (x₁, y₁)
       - 关键点 2: 目标物体的位置 (x₂, y₂)
       - ...
       这些空间关键点坐标对于机器人决定"往哪里推"至关重要！
    
    4. 与原始论文的关系：
       来自论文 "Deep Spatial Autoencoders for Visuomotor Learning" (Finn et al., 2015)：
       "学习空间特征编码，将图像压缩为一组关键点的坐标，这些坐标对应于机器人需要关注的重要位置。"
    """

    def __init__(self, input_shape, num_kp=None):
        """
        Args:
            input_shape (list): (C, H, W) input feature map shape. 例如：(512, 3, 3)
            num_kp (int): number of keypoints in output. If None, output will have the same number of channels as input.
                         关键点数量，默认为 None 则输出与输入相同的通道数
        """
        super().__init__()

        assert len(input_shape) == 3
        self._in_c, self._in_h, self._in_w = input_shape  # 例如：512, 3, 3

        if num_kp is not None:
            # 使用 1x1 卷积将通道数转换为关键点数量
            self.nets = torch.nn.Conv2d(self._in_c, num_kp, kernel_size=1)
            self._out_c = num_kp  # 例如：32
        else:
            self.nets = None
            self._out_c = self._in_c

        # we could use torch.linspace directly but that seems to behave slightly differently than numpy
        # and causes a small degradation in pc_success of pre-trained models.
        # 创建归一化坐标网格 (-1 到 1)
        pos_x, pos_y = np.meshgrid(np.linspace(-1.0, 1.0, self._in_w), np.linspace(-1.0, 1.0, self._in_h))
        pos_x = torch.from_numpy(pos_x.reshape(self._in_h * self._in_w, 1)).float()  # (H*W, 1)
        pos_y = torch.from_numpy(pos_y.reshape(self._in_h * self._in_w, 1)).float()  # (H*W, 1)
        # register as buffer so it's moved to the correct device.
        self.register_buffer("pos_grid", torch.cat([pos_x, pos_y], dim=1))  # (H*W, 2)

    def forward(self, features: Tensor) -> Tensor:
        """
        Args:
            features: (B, C, H, W) input feature maps. 例如：(128, 512, 3, 3)
        Returns:
            (B, K, 2) image-space coordinates of keypoints. 例如：(128, 32, 2)
        """
        if self.nets is not None:
            features = self.nets(features)  # (B, num_kp, H, W) 例如：(128, 32, 3, 3)

        # [B, K, H, W] -> [B * K, H * W] where K is number of keypoints
        # 展平空间维度
        features = features.reshape(-1, self._in_h * self._in_w)  # (B*K, H*W)
        
        # 2d softmax normalization 在空间维度上进行 softmax
        attention = F.softmax(features, dim=-1)  # (B*K, H*W)
        
        # [B * K, H * W] x [H * W, 2] -> [B * K, 2] for spatial coordinate mean in x and y dimensions
        # 计算期望坐标（加权平均）
        expected_xy = attention @ self.pos_grid  # (B*K, 2)
        
        # reshape to [B, K, 2] 重塑为 (B, K, 2)
        feature_keypoints = expected_xy.view(-1, self._out_c, 2)  # (B, num_kp, 2)

        return feature_keypoints  # (batch_size, num_keypoints, 2)


class DiffusionRgbEncoder(nn.Module):
    """Encodes an RGB image into a 1D feature vector.

    Includes the ability to normalize and crop the image first.
    
    RGB 图像编码器：将 RGB 图像编码为 1D 特征向量
    """

    def __init__(self, config: DiffusionConfig):
        super().__init__()
        # Set up optional preprocessing.
        if config.crop_shape is not None:
            self.do_crop = True
            # Always use center crop for eval
            self.center_crop = torchvision.transforms.CenterCrop(config.crop_shape)  # (84, 84)
            if config.crop_is_random:
                self.maybe_random_crop = torchvision.transforms.RandomCrop(config.crop_shape)  # 训练时使用随机裁剪
            else:
                self.maybe_random_crop = self.center_crop
        else:
            self.do_crop = False

        # Set up backbone. 使用 ResNet 作为骨干网络
        backbone_model = getattr(torchvision.models, config.vision_backbone)(
            weights=config.pretrained_backbone_weights
        )
        # Note: This assumes that the layer4 feature map is children()[-3]
        # TODO(alexander-soare): Use a safer alternative.
        # 移除最后的全连接层和池化层，保留卷积层
        self.backbone = nn.Sequential(*(list(backbone_model.children())[:-2]))
        # 输出特征维度：512 (对于 ResNet18)
        
        if config.use_group_norm:
            if config.pretrained_backbone_weights:
                raise ValueError(
                    "You can't replace BatchNorm in a pretrained model without ruining the weights!"
                )
            # 将 BatchNorm 替换为 GroupNorm
            self.backbone = _replace_submodules(
                root_module=self.backbone,
                predicate=lambda x: isinstance(x, nn.BatchNorm2d),
                func=lambda x: nn.GroupNorm(num_groups=x.num_features // 16, num_channels=x.num_features),
            )

        # Set up pooling and final layers.
        # Use a dry run to get the feature map shape.
        # The dummy input should take the number of image channels from `config.image_features` and it should
        # use the height and width from `config.crop_shape` if it is provided, otherwise it should use the
        # height and width from `config.image_features`.

        # Note: we have a check in the config class to make sure all images have the same shape.
        images_shape = next(iter(config.image_features.values())).shape  # (3, 96, 96)
        dummy_shape_h_w = config.crop_shape if config.crop_shape is not None else images_shape[1:]  # (84, 84)
        dummy_shape = (1, images_shape[0], *dummy_shape_h_w)  # (1, 3, 84, 84)
        
        # 通过一次前向传播获取骨干网络输出特征图形状
        feature_map_shape = get_output_shape(self.backbone, dummy_shape)[1:]  # (512, 3, 3)

        # SpatialSoftmax 池化层，将空间特征压缩为关键点坐标
        self.pool = SpatialSoftmax(feature_map_shape, num_kp=config.spatial_softmax_num_keypoints)
        # 输出：(batch, num_keypoints=32, 2)
        
        self.feature_dim = config.spatial_softmax_num_keypoints * 2  # 32 * 2 = 64
        
        # 最终线性层（恒等映射，保持维度不变）
        self.out = nn.Linear(config.spatial_softmax_num_keypoints * 2, self.feature_dim)  # Linear(64, 64)
        self.relu = nn.ReLU()

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: (B, C, H, W) image tensor with pixel values in [0, 1]. 例如：(128, 3, 96, 96)
        Returns:
            (B, D) image feature. 例如：(128, 64)
        """
        # Preprocess: maybe crop (if it was set up in the __init__).
        if self.do_crop:
            if self.training:  # noqa: SIM108
                x = self.maybe_random_crop(x)  # 训练时随机裁剪
            else:
                # Always use center crop for eval.
                x = self.center_crop(x)  # 评估时中心裁剪
        # Extract backbone feature. 提取骨干特征
        # backbone 输出：(B, 512, 3, 3)
        # pool 输出：(B, 32, 2)
        # flatten 后：(B, 64)
        x = torch.flatten(self.pool(self.backbone(x)), start_dim=1)  # (B, 64)
        
        # Final linear layer with non-linearity. 最终线性变换 + ReLU
        x = self.relu(self.out(x))  # (B, 64)
        
        return x


def _replace_submodules(
    root_module: nn.Module, predicate: Callable[[nn.Module], bool], func: Callable[[nn.Module], nn.Module]
) -> nn.Module:
    """
    Args:
        root_module: The module for which the submodules need to be replaced
        predicate: Takes a module as an argument and must return True if the that module is to be replaced.
        func: Takes a module as an argument and returns a new module to replace it with.
    Returns:
        The root module with its submodules replaced.
    
    替换模块中的子模块（用于将 BatchNorm 替换为 GroupNorm）
    """
    if predicate(root_module):
        return func(root_module)

    replace_list = [k.split(".") for k, m in root_module.named_modules(remove_duplicate=True) if predicate(m)]
    for *parents, k in replace_list:
        parent_module = root_module
        if len(parents) > 0:
            parent_module = root_module.get_submodule(".".join(parents))
        if isinstance(parent_module, nn.Sequential):
            src_module = parent_module[int(k)]
        else:
            src_module = getattr(parent_module, k)
        tgt_module = func(src_module)
        if isinstance(parent_module, nn.Sequential):
            parent_module[int(k)] = tgt_module
        else:
            setattr(parent_module, k, tgt_module)
    # verify that all BN are replaced
    assert not any(predicate(m) for _, m in root_module.named_modules(remove_duplicate=True))
    return root_module


class DiffusionSinusoidalPosEmb(nn.Module):
    """1D sinusoidal positional embeddings as in Attention is All You Need.
    
    正弦位置编码，用于编码扩散时间步
    """

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim  # 嵌入维度，例如：128

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: (B,) 时间步张量
        Returns:
            (B, dim) 正弦位置编码
        """
        device = x.device
        half_dim = self.dim // 2  # 64
        emb = math.log(10000) / (half_dim - 1)  # 计算频率衰减因子
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)  # (half_dim,) 频率向量
        emb = x.unsqueeze(-1) * emb.unsqueeze(0)  # (B, half_dim) 外积
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)  # (B, dim) 拼接 sin 和 cos
        
        return emb


class DiffusionConv1dBlock(nn.Module):
    """Conv1d --> GroupNorm --> Mish
    
    1D 卷积块：卷积 -> 组归一化 -> Mish 激活
    """

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),  # 1D 卷积，保持序列长度
            nn.GroupNorm(n_groups, out_channels),  # 组归一化
            nn.Mish(),  # Mish 激活函数
        )

    def forward(self, x):
        return self.block(x)  # (B, out_channels, T)


class DiffusionConditionalUnet1d(nn.Module):
    """A 1D convolutional UNet with FiLM modulation for conditioning.

    Note: this removes local conditioning as compared to the original diffusion policy code.
    
    1D 卷积 UNet，带有 FiLM 调制用于条件化
    """

    def __init__(self, config: DiffusionConfig, global_cond_dim: int):
        super().__init__()

        self.config = config

        # Encoder for the diffusion timestep.
        # 时间步编码器：将扩散时间步编码为向量
        self.diffusion_step_encoder = nn.Sequential(
            DiffusionSinusoidalPosEmb(config.diffusion_step_embed_dim),  # 正弦位置编码 (B, 128)
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),  # Linear(128, 512)
            nn.Mish(),  # Mish 激活
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),  # Linear(512, 128)
        )

        # The FiLM conditioning dimension.
        # FiLM 条件维度：时间步嵌入 + 全局条件
        cond_dim = config.diffusion_step_embed_dim + global_cond_dim  # 128 + 132 = 260

        # In channels / out channels for each downsampling block in the Unet's encoder. For the decoder, we
        # just reverse these.
        # UNet 编码器的输入/输出通道数
        in_out = [(config.action_feature.shape[0], config.down_dims[0])] + list(
            zip(config.down_dims[:-1], config.down_dims[1:], strict=True)
        )
        # 例如：[(2, 512), (512, 1024), (1024, 2048)]

        # Unet encoder.
        common_res_block_kwargs = {
            "cond_dim": cond_dim,
            "kernel_size": config.kernel_size,  # 5
            "n_groups": config.n_groups,  # 8
            "use_film_scale_modulation": config.use_film_scale_modulation,  # True
        }
        self.down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            self.down_modules.append(
                nn.ModuleList(
                    [
                        DiffusionConditionalResidualBlock1d(dim_in, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Downsample as long as it is not the last block.
                        nn.Conv1d(dim_out, dim_out, 3, 2, 1) if not is_last else nn.Identity(),  # 下采样卷积，stride=2
                    ]
                )
            )

        # Processing in the middle of the auto-encoder.
        # UNet 中间处理模块
        self.mid_modules = nn.ModuleList(
            [
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
            ]
        )

        # Unet decoder.
        # UNet 解码器
        self.up_modules = nn.ModuleList([])
        for ind, (dim_out, dim_in) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            self.up_modules.append(
                nn.ModuleList(
                    [
                        # dim_in * 2, because it takes the encoder's skip connection as well
                        DiffusionConditionalResidualBlock1d(dim_in * 2, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Upsample as long as it is not the last block.
                        nn.ConvTranspose1d(dim_out, dim_out, 4, 2, 1) if not is_last else nn.Identity(),  # 上采样转置卷积
                    ]
                )
            )

        # 最终输出卷积层
        self.final_conv = nn.Sequential(
            DiffusionConv1dBlock(config.down_dims[0], config.down_dims[0], kernel_size=config.kernel_size),
            nn.Conv1d(config.down_dims[0], config.action_feature.shape[0], 1),  # 输出到 action_dim
        )

    def forward(self, x: Tensor, timestep: Tensor | int, global_cond=None) -> Tensor:
        """
        Args:
            x: (B, T, input_dim) tensor for input to the Unet. 例如：(64, 16, 2)
            timestep: (B,) tensor of (timestep_we_are_denoising_from - 1). 例如：(64,)
            global_cond: (B, global_cond_dim) 例如：(64, 132)
            output: (B, T, input_dim)
        Returns:
            (B, T, input_dim) diffusion model prediction. 例如：(64, 16, 2)
        """
        # For 1D convolutions we'll need feature dimension first.
        # 重排维度以便进行 1D 卷积：(B, T, D) -> (B, D, T)
        x = einops.rearrange(x, "b t d -> b d t")  # (64, 2, 16)

        # 编码时间步
        timesteps_embed = self.diffusion_step_encoder(timestep)  # (B, 128)

        # If there is a global conditioning feature, concatenate it to the timestep embedding.
        # 拼接时间步嵌入和全局条件
        if global_cond is not None:
            global_feature = torch.cat([timesteps_embed, global_cond], axis=-1)  # (B, 260)
        else:
            global_feature = timesteps_embed

        # Run encoder, keeping track of skip features to pass to the decoder.
        # 运行编码器，保存跳跃连接特征
        encoder_skip_features: list[Tensor] = []
        for resnet, resnet2, downsample in self.down_modules:
            x = resnet(x, global_feature)  # 第一个残差块
            x = resnet2(x, global_feature)  # 第二个残差块
            encoder_skip_features.append(x)  # 保存跳跃连接
            x = downsample(x)  # 下采样（除了最后一个块）

        # Run middle modules
        # 运行中间模块
        for mid_module in self.mid_modules:
            x = mid_module(x, global_feature)

        # Run decoder, using the skip features from the encoder.
        # 运行解码器，使用编码器的跳跃连接
        for resnet, resnet2, upsample in self.up_modules:
            x = torch.cat((x, encoder_skip_features.pop()), dim=1)  # 拼接跳跃连接特征
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)  # 上采样（除了最后一个块）

        # 最终卷积
        x = self.final_conv(x)

        # 重排回原始维度：(B, D, T) -> (B, T, D)
        x = einops.rearrange(x, "b d t -> b t d")
        return x


class DiffusionConditionalResidualBlock1d(nn.Module):
    """ResNet style 1D convolutional block with FiLM modulation for conditioning.
    
    带有 FiLM 调制的 ResNet 风格 1D 卷积残差块
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        cond_dim: int,
        kernel_size: int = 3,
        n_groups: int = 8,
        # Set to True to do scale modulation with FiLM as well as bias modulation (defaults to False meaning
        # FiLM just modulates bias).
        use_film_scale_modulation: bool = False,
    ):
        super().__init__()

        self.use_film_scale_modulation = use_film_scale_modulation
        self.out_channels = out_channels

        # 第一个卷积块
        self.conv1 = DiffusionConv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups)

        # FiLM modulation (https://huggingface.co/papers/1709.07871) outputs per-channel bias and (maybe) scale.
        # FiLM 调制器：从条件向量生成偏置和（可选）缩放参数
        cond_channels = out_channels * 2 if use_film_scale_modulation else out_channels
        self.cond_encoder = nn.Sequential(nn.Mish(), nn.Linear(cond_dim, cond_channels))

        # 第二个卷积块
        self.conv2 = DiffusionConv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups)

        # A final convolution for dimension matching the residual (if needed).
        # 残差连接的 1x1 卷积（如果输入输出通道不同）
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x: Tensor, cond: Tensor) -> Tensor:
        """
        Args:
            x: (B, in_channels, T) 例如：(64, 2, 16)
            cond: (B, cond_dim) 例如：(64, 260)
        Returns:
            (B, out_channels, T) 例如：(64, 512, 16)
        """
        out = self.conv1(x)  # (B, out_channels, T)

        # Get condition embedding. Unsqueeze for broadcasting to `out`, resulting in (B, out_channels, 1).
        # 从条件向量生成 FiLM 参数
        cond_embed = self.cond_encoder(cond).unsqueeze(-1)  # (B, cond_channels, 1)
        
        if self.use_film_scale_modulation:
            # Treat the embedding as a list of scales and biases.
            # 将条件嵌入分为缩放和偏置两部分
            scale = cond_embed[:, : self.out_channels]  # (B, out_channels, 1)
            bias = cond_embed[:, self.out_channels :]  # (B, out_channels, 1)
            out = scale * out + bias  # FiLM 调制：缩放 + 偏置
        else:
            # Treat the embedding as biases.
            # 仅使用偏置调制
            out = out + cond_embed  # (B, out_channels, T) + (B, out_channels, 1)

        out = self.conv2(out)  # 第二个卷积块
        out = out + self.residual_conv(x)  # 残差连接
        
        return out
